parte2:
  outputs:
    dev:
      dbname: curso_dbt
      host: dpg-d3k4tem3jp1c73au50h0-a.oregon-postgres.render.com
      pass: "{{ env_var('POSTGRE_PASSWORD') }}"
      port: 5432
      schema: parte2
      threads: 1
      type: postgres
      user: admin
  target: dev